
defaultEntryPoints = ["http", "https"]


[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]


[api]


[ping]


[acme]
email = "pjpjunior@gmail.com"
storage = "/etc/traefik/acme/acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
acmeLogging = true
onHostRule = true


[acme.httpChallenge]
   entryPoint = "http"

[[acme.domains]]
 mail = "blog.paulotech.com.br"

[acme.dnsChallenge]
  provider = "manual"





