################################################################

defaultEntryPoints = ["http", "https"]

################################################################
# Entrypoints configuration
################################################################

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]


################################################################
# API and dashboard configuration
################################################################

[api]

################################################################
# Ping configuration
################################################################

[ping]

################################################################
# Docker configuration backend
################################################################

[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.


[acme]
email = "seu_email@gmail.com"
storage = "/etc/traefik/acme/acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
entryPoint = "https"
acmeLogging = true
onHostRule = true


[acme.httpChallenge]
   entryPoint = "http"

[[acme.domains]]
  main = "seu_site.com.br"
  sans = ["www.seu_site.com.br", "blog.seu_site.com.br"]
